#if DEBUG
import CoreGraphics
import CoreImage
import Darwin
import Foundation
#if os(iOS) && MEMOMARK_SHARE_EXTENSION
import os
#endif

/// Experimental disk-backed raster. The only owned pixel buffer is one strip.
/// ImageIO consumes the read-only map synchronously before it is unmapped.
@MainActor
enum CPUFileRasterExport {
    /// Larger bounded strips amortize Core Image render setup without restoring
    /// a full-canvas pixel allocation. Width is validated by withMappedRaster.
    static func stripRows(forWidth width: Int) -> Int {
        precondition((1...16_384).contains(width))
        return min(64, (2 * 1024 * 1024) / (width * 4))
    }
    /// Call only while holding the shared execution lease. Each Live Photo
    /// work directory is generated by the existing processor as a UUID.
    static func cleanupInterruptedRasters(inProcessingRoot root: URL) throws {
        guard FileManager.default.fileExists(atPath: root.path) else { return }
        for folder in try FileManager.default.contentsOfDirectory(at: root,
            includingPropertiesForKeys: [.isDirectoryKey, .isSymbolicLinkKey]) {
            let values = try folder.resourceValues(forKeys: [.isDirectoryKey, .isSymbolicLinkKey])
            guard UUID(uuidString: folder.lastPathComponent) != nil,
                  values.isDirectory == true, values.isSymbolicLink != true else { continue }
            try cleanupInterruptedRasters(in: folder)
        }
    }

    static func cleanupInterruptedRasters(in exportFolder: URL) throws {
        let folder = exportFolder.appendingPathComponent(".cpu-raster-work", isDirectory: true)
        guard FileManager.default.fileExists(atPath: folder.path) else { return }
        for file in try FileManager.default.contentsOfDirectory(at: folder,
            includingPropertiesForKeys: [.isRegularFileKey, .isSymbolicLinkKey]) {
            let values = try file.resourceValues(forKeys: [.isRegularFileKey, .isSymbolicLinkKey])
            guard file.pathExtension == "rgba", UUID(uuidString: file.deletingPathExtension().lastPathComponent) != nil,
                  values.isRegularFile == true, values.isSymbolicLink != true else { continue }
            try FileManager.default.removeItem(at: file)
        }
    }

    static func writeJPEG(image: CIImage, context: CIContext, to url: URL,
                          sourceProperties: [CFString: Any], exportDescription: String,
                          captureDate: Date?, writer: MetadataPreservingImageWriter) throws -> URL {
        try withMappedRaster(image: image, context: context, to: url) { raster in
            try writer.write(cgImage: raster, to: url, sourceProperties: sourceProperties,
                exportDescription: exportDescription, captureDate: captureDate)
        }
    }

    /// The synchronous encoder must finish consuming the raster before returning.
    /// Only the output URL escapes; the provider and mapping remain scoped here.
    static func withMappedRaster(image: CIImage, context: CIContext, to url: URL,
                                 encode: (CGImage) throws -> URL) throws -> URL {
        try Task.checkCancellation()
        guard image.extent.width.isFinite, image.extent.height.isFinite,
              image.extent.width >= 1, image.extent.height >= 1,
              image.extent.width <= 16_384, image.extent.height <= 16_384 else {
            throw RecordCardExportError.renderFailed
        }
        let width = Int(image.extent.width.rounded())
        let height = Int(image.extent.height.rounded())
        let rowSize = width.multipliedReportingOverflow(by: 4)
        let fileSize = rowSize.partialValue.multipliedReportingOverflow(by: height)
        guard width > 0, height > 0, !rowSize.overflow, !fileSize.overflow,
              fileSize.partialValue <= 512 * 1024 * 1024,
              let colorSpace = CGColorSpace(name: CGColorSpace.sRGB) else {
            throw RecordCardExportError.renderFailed
        }
        let folder = url.deletingLastPathComponent().appendingPathComponent(".cpu-raster-work", isDirectory: true)
        try FileManager.default.createDirectory(at: folder, withIntermediateDirectories: true)
        let free = try FileManager.default.attributesOfFileSystem(forPath: folder.path)[.systemFreeSize] as? NSNumber
        guard let free, free.int64Value > Int64(fileSize.partialValue) * 2 else {
            throw RecordCardExportError.writeFailed
        }
        let rasterURL = folder.appendingPathComponent(UUID().uuidString).appendingPathExtension("rgba")
        guard FileManager.default.createFile(atPath: rasterURL.path, contents: nil) else {
            throw RecordCardExportError.temporaryFileCreateFailed
        }
        defer { try? FileManager.default.removeItem(at: rasterURL) }
        let output = try FileHandle(forWritingTo: rasterURL)
        do {
            let rowsPerStrip = stripRows(forWidth: width)
            var pixels = [UInt8](repeating: 0, count: rowSize.partialValue * rowsPerStrip)
            // Bitmap output is top-to-bottom within each bounds rectangle.
            // Visit rectangles from the top of Core Image's coordinate space;
            // flipping the recipe would reverse rows inside every strip.
            let normalized = image.transformed(by: CGAffineTransform(
                translationX: -image.extent.minX, y: -image.extent.minY))
            for row in stride(from: 0, to: height, by: rowsPerStrip) {
                try Task.checkCancellation()
                let rows = min(rowsPerStrip, height - row)
                try pixels.withUnsafeMutableBytes { bytes in
                    guard let address = bytes.baseAddress else { throw RecordCardExportError.renderFailed }
                    context.render(normalized, toBitmap: address, rowBytes: rowSize.partialValue,
                        bounds: CGRect(x: 0, y: height - row - rows, width: width, height: rows), format: .RGBA8,
                        colorSpace: colorSpace)
                }
                try output.write(contentsOf: pixels.withUnsafeBytes { Data($0.prefix(rowSize.partialValue * rows)) })
            }
            try output.synchronize()
            try output.close()
        } catch {
            try? output.close()
            throw error
        }
        context.clearCaches()
        record("extension.cpuRaster.stripsWritten")
        let descriptor = open(rasterURL.path, O_RDONLY)
        guard descriptor >= 0 else { throw RecordCardExportError.writeFailed }
        defer { close(descriptor) }
        guard let mapping = mmap(nil, fileSize.partialValue, PROT_READ, MAP_PRIVATE, descriptor, 0),
              mapping != MAP_FAILED else { throw RecordCardExportError.writeFailed }
        defer { munmap(mapping, fileSize.partialValue) }
        _ = madvise(mapping, fileSize.partialValue, MADV_SEQUENTIAL)
        record("extension.cpuRaster.beforeImageIOEncode")
        return try autoreleasepool {
            guard let provider = CGDataProvider(dataInfo: nil, data: mapping,
                size: fileSize.partialValue, releaseData: { _, _, _ in }),
                  let raster = CGImage(width: width, height: height, bitsPerComponent: 8,
                    bitsPerPixel: 32, bytesPerRow: rowSize.partialValue, space: colorSpace,
                    bitmapInfo: CGBitmapInfo(rawValue: CGImageAlphaInfo.premultipliedLast.rawValue),
                    provider: provider, decode: nil, shouldInterpolate: false, intent: .defaultIntent) else {
                throw RecordCardExportError.renderFailed
            }
            return try encode(raster)
        }
    }

    private static func record(_ event: String) {
#if os(iOS) && MEMOMARK_SHARE_EXTENSION
        MemoMarkBackgroundProbe.record(event, detail: "availableMemory=\(os_proc_available_memory())")
#endif
    }
}
#endif
